name = "0supply"
author = "Gabriel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb75a0b0b06cf83cb61ee05d8070cd24d858bf9aa72033617f652d6a69bba106"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
