name = "0supply"
author = "Gabriel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf4bedb24eeed6f161fc77fe35232598ce1a644b956a142bc5a68e4a2c4862d9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
