name = "0supply"
author = "Gabriel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b6008d18ea34f08b5579e6f6579885ea774ec14a854f72665a728ef21a38ad78"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
